CarOwnerHariz1A/lab5-10[laravel]/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});




Route::resource('/owner','OwnerController');//->middleware('auth');

Route::resource('/car','CarController');
/////////////////////////////////////////////
//lab6
///////////////////
Route::resource('/driver','DriverController');

Route::get('/alldriver','DriverController@index');

Route::post('/owner/create','OwnerController@store');

Route::get('/delowner/{owner}','OwnerController@destroy')->name('destroy1');
Route::get('/delowner/{car}','CarController@destroy')->name('destroy2');

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

CarOwnerHariz1A/lab5-10[laravel]/resources/views/cars.blade.php
@extends('layouts.main')

@section('content')

    <h1>Cars List</h1>
    <!--<a class="btn btn-outline-primary float-right"><ion-icon name="person-add"></ion-icon></a>-->
    <table class="table table-bordered">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">RegNum</th>
            <th scope="col">Manufacturer</th>
            <th scope="col">Model</th>
            <th scope="col">YearMade</th>
            <th scope="col">Owner</th>
            <th scope="col">Action</th>
        </tr>
        </thead>
        <tbody>
        @if ($i==0)
            <tr>
                <td colspan="6"> No Data </td>
            </tr>
        @else   
            @foreach($cars as $car)
                <tr>
                    <th scope="row"> {{$i++}} </th>
                    <td>{{$car->RegNum}}</td>
                    <td>
                        
                        {{$car->Manufacturer}}
                        
                    </td>
                        
                    <td>
                        {{$car->Model}}
                    </td>
                    <td>
                        {{$car->YearMade}}
                    </td>
                    <td>
                        {{$car->Owner['name']}}
                    </td>
                    <td>
                        <a href="{{route('car.edit', $car->id)}}"><ion-icon name="create"></ion-icon></a>
                        <a href="{{route('destroy2', $car->id)}}"><ion-icon name="trash"></ion-icon></a>
                        
                    </td>
                </tr>
            @endforeach
        @endif
        </tbody>
    </table>
@endsection

CarOwnerHariz1A/lab5-10[laravel]/resources/views/drivers.blade.php
@extends('layouts.main')

@section('content')

    <h1>Driver List</h1>
    <!--<a class="btn btn-outline-primary float-right"><ion-icon name="person-add"></ion-icon></a>-->
    <table class="table table-bordered">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">ICno</th>
            <th scope="col">HPno</th>
            <th scope="col">DrivingLicense</th>
            <th scope="col">ExpiryDate</th>
            <th scope="col">Action</th>
        </tr>
        </thead>
        <tbody>
        @if ($i==0)
            <tr>
                <td colspan="6"> No Data </td>
            </tr>
        @else   
            @foreach($drivers as $driver)
                <tr>
                    <th scope="row"> {{$i++}} </th>
                    <td>{{$driver->name}}</td>
                
                    <td>
                        {{$driver->ICno}}
                    </td>
                    <td>
                        {{$driver->HPno}}
                    </td>
                    <td>
                        {{$driver->drivingLicenseNo}}
                    </td>
                    <td>
                        {{$driver->expiryDate}}
                    </td>
                    <td>
                        
                        <ion-icon name="trash"></ion-icon>
                    </td>
                </tr>
            @endforeach
        @endif
        </tbody>
    </table>
@endsection

CarOwnerHariz1A/lab5-10[laravel]/resources/views/editcar.blade.php
@extends('layouts.main')

@section('content')
    <h1>Update Car Info</h1>
    <form action="{{route('car.update',$car->id)}}" method="post">
        @csrf
        @method('PUT')
        <div class="form-group">
            <label for="RegNum">Reg Number</label>
            <input  type="text" name="RegNum" value="{{$car->RegNum}}" class="form-control">
        </div>

        <div class="form-group">
            <label for="Manufacturer">Manufacturer</label>
            <input  type="text" name="Manufacturer" value="{{$car->Manufacturer}}" class="form-control">
        </div>

        <div class="form-group">
            <label for="Model">Model</label>
            <input  type="text" name="Model" value="{{$car->Model}}" class="form-control">
        </div>


        <div class="form-group">
            <label for="YearMade">Year Made</label>
            <input  type="text" name="YearMade" value="{{$car->YearMade}}" class="form-control">
        </div>

        <div class="form-group">
            <label for="Owner">Owner</label>
            <select name="owner_id" class="custom-select">
                @if($car->owner !=null)
                    <option selected value="{{$car->owner_id}}">{{$car['owner']->name}}</option>
                @else 
                    <option selected value="">Please Select</option>
                @endif
                @foreach($owners as $owner)
                    <option value="{{$owner->id}}">{{$owner->name}}</option>
                @endforeach
                
                <option value="">-- No Owner --</option>
            </select>
        </div>

        <div class="form-group">
            <label for="Driver">Driver</label>
            @forelse($car->drivers as $d)
                <li>{{$d->name}}</li>
            @empty  
                <p>No Driver</p>
            @endforelse
            <select name="driver[]" class="custom-select" multiple>
            
                @foreach($drivers as $driver)
                    <option value="{{$driver->id}}">{{$driver->name}}</option>
                @endforeach
                
                <option value="">-- No Owner --</option>
            </select>

        </div>



        <input type="submit" class="btn btn-primary" values="Save">
        <a class="btn btn-warning" href="/car">Cancel</a>
    </form>
    <br>
@endsection

CarOwnerHariz1A/lab5-10[laravel]/resources/views/editowner.blade.php
@extends('layouts.main')

@section('content')
    <h1>Update OOwner's Info</h1>
    <form action="{{route('owner.update',$owner->id)}}" method="post">
        @csrf
        @method('PUT')
        <div class="form-group">
            <label for="name">Name</label>
            <input  type="text" name="name" value="{{$owner->name}}" class="form-control">
        </div>

        <div class="form-group">
            <label for="email">Email</label>
            <input  type="email" name="email" value="{{$owner->email}}" class="form-control">
        </div>         

        <input type="submit" class="btn btn-primary" values="Edit">
        <a class="btn btn-warning" href="/owner">Cancel</a>
    </form>
    <br>
    <h2>Cars Owned</h2>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Reg Number</th>
            <th scope="col">Manufacturer</th>
            <th scope="col">Model</th>
            <th scope="col">Year Made</th>
        </tr>
        </thead>
        <tbody>
        <?php $i=1 ?>
        @foreach($cars as $car)
            <tr>
                <th scope="row">{{$i++}}</th>
                <td>{{$car->RegNum}}</td>
                <td>{{$car->Manufacturer}}</td>
                <td>{{$car->Model}}</td>
                <td>{{$car->YearMade}}</td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endsection

CarOwnerHariz1A/lab5-10[laravel]/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in! <h3><a href="{{ url('/owner') }}">To the Project</a></h3>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

CarOwnerHariz1A/lab5-10[laravel]/resources/views/owner.blade.php
@extends('layouts.main')

@section('content')

    <h1>Car Owner List</h1>

    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
    Add Owner
    </button>
    <br><br>


    <!--<a class="btn btn-outline-primary float-right"><ion-icon name="person-add"></ion-icon></a>-->
    <table class="table table-bordered">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Car</th>
            <th scope="col">Action</th>
        </tr>
        </thead>
        <tbody>
        @if ($i==0)
            <tr>
                <td colspan="5"> No Data </td>
            </tr>
        @else   
            @foreach($owners as $owner)
                <tr>
                    <th scope="row"> {{$i++}} </th>
                    <td>{{$owner->name}}</td>
                    <td>
                        <ion-icon name="mail"></ion-icon>
                        {{$owner->email}}
                        <br>
                    </td>

                    <td>
                        @foreach($owner->cars as $car)
                        <ion-icon name="car"></ion-icon>
                        {{$car->RegNum}} {{$car->Manufacturer}}
                        {{$car->Model}}<br>
                        @endforeach
                    </td>
                    <td>
                        <a href="{{route('owner.edit', $owner->id)}}"><ion-icon name="create"></ion-icon></a>
                        <a href="{{route('destroy1', $owner->id)}}"><ion-icon name="trash"></ion-icon></a>
                        <a href="{{route('owner.show', $owner->id)}}"><ion-icon name="analytics"></ion-icon></a>
                    </td>
                </tr>
            @endforeach
        @endif
        </tbody>
    </table>
    <!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
        <!--MODAL CONTENT HERE!-->
      <div class="modal-body">
      <form action="/owner/create" method="POST">
      @csrf


  <div class="form-group">
    <label for="exampleInputEmail1">Name</label>
    <input name="name" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter Your Name">
    <small id="emailHelp" class="form-text text-muted">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Email</label>
    <input name="email" type="text" class="form-control" id="exampleInputPassword1" placeholder="Enter Your Email">
  </div>
  
  <button type="submit" class="btn btn-primary">Add</button>
</form>
      </div>
        
      <div  class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
      <!--MODAL ENDS HERE!-->
@endsection

CarOwnerHariz1A/lab5-10[laravel]/resources/views/showowner.blade.php
@extends('layouts.main')

@section('content')
    <h1>Owner's Details</h1>

    <div class="card">
        <h5 class="card-header">{{$owner->name}}</h5>
        <div class="card-body">
            <h5 class="card-title"><ion-icon name="mail"></ion-icon>{{$owner->email}}</h5>
            <!--<h5 class="card-title"><ion-icon name="phone-portrait"></ion-icon>{{$owner->HPno}}</h5>-->
            <a href="{{route('owner.edit',$owner->id)}}" class="btn btn-primary">Edit</a>
            <a href="{{url('/owner')}}" class="btn btn-warning">Back</a>
        </div>
    </div>
@endsection